### ISSUE TITLE
ImportError thrown during pi calculation

### ISSUE THREAD

**Issue by elmiko** [radanalyticsio/tutorial-sparkpi-python-flask#9]
Occasionally when running this application on OpenShift, an `ImportError` is thrown from Python about not being able to find `werkzeug.test`. I am not sure why this happens, and it seems to go away when I redeploy or rebuild, but not always.

the output is similar to this

```
oshinko v0.4.0
Default spark image: radanalyticsio/openshift-spark:2.2-latest
Didn't find cluster cluster-00686c, creating ephemeral cluster
Using ephemeral cluster cluster-00686c
Waiting for spark master http://cluster-00686c-ui:8080  to be available ...
Waiting for spark master http://cluster-00686c-ui:8080  to be available ...
Waiting for spark master http://cluster-00686c-ui:8080  to be available ...
Waiting for spark master http://cluster-00686c-ui:8080  to be available ...
Waiting for spark master http://cluster-00686c-ui:8080  to be available ...
Waiting for spark master http://cluster-00686c-ui:8080  to be available ...
Waiting for spark master http://cluster-00686c-ui:8080  to be available ...
Waiting for spark master http://cluster-00686c-ui:8080  to be available ...
Waiting for spark master http://cluster-00686c-ui:8080  to be available ...
Waiting for spark master http://cluster-00686c-ui:8080  to be available ...
Waiting for spark master http://cluster-00686c-ui:8080  to be available ...
Waiting for spark master http://cluster-00686c-ui:8080  to be available ...
Waiting for spark master http://cluster-00686c-ui:8080  to be available ...
Waiting for spark master http://cluster-00686c-ui:8080  to be available ...
Waiting for spark workers (0/0 alive) ...
All spark workers alive
spark-submit --master spark://cluster-00686c:7077 /opt/app-root/src/app.py
 * Running on http://0.0.0.0:8080/  (Press CTRL+C to quit)
172.17.0.6 - - [19/Oct/2017 21:55:50] "GET /favicon.ico HTTP/1.1" 404 -
172.17.0.6 - - [19/Oct/2017 21:56:01] "GET / HTTP/1.1" 200 -
17/10/19 21:56:14 INFO SparkContext: Running Spark version 2.2.0
17/10/19 21:56:14 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
17/10/19 21:56:14 INFO SparkContext: Submitted application: PythonPi
17/10/19 21:56:14 INFO SecurityManager: Changing view acls to: default
17/10/19 21:56:14 INFO SecurityManager: Changing modify acls to: default
17/10/19 21:56:14 INFO SecurityManager: Changing view acls groups to: 
17/10/19 21:56:14 INFO SecurityManager: Changing modify acls groups to: 
17/10/19 21:56:14 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(default); groups with view permissions: Set(); users  with modify permissions: Set(default); groups with modify permissions: Set()
17/10/19 21:56:14 INFO Utils: Successfully started service 'sparkDriver' on port 38647.
17/10/19 21:56:15 INFO SparkEnv: Registering MapOutputTracker
17/10/19 21:56:15 INFO SparkEnv: Registering BlockManagerMaster
17/10/19 21:56:15 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
17/10/19 21:56:15 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
17/10/19 21:56:15 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-4b881a99-736f-4cc1-ad5f-5ab33f804035
17/10/19 21:56:15 INFO MemoryStore: MemoryStore started with capacity 366.3 MB
17/10/19 21:56:15 INFO SparkEnv: Registering OutputCommitCoordinator
17/10/19 21:56:15 INFO Utils: Successfully started service 'SparkUI' on port 4040.
17/10/19 21:56:15 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://172.17.0.5:4040 
17/10/19 21:56:15 INFO SparkContext: Added file file:/opt/app-root/src/app.py at spark://172.17.0.5:38647/files/app.py with timestamp 1508450175665
17/10/19 21:56:15 INFO Utils: Copying /opt/app-root/src/app.py to /tmp/spark-b4580f30-0651-4dbf-8b46-04ebd4b8e515/userFiles-15807ae6-344c-4066-a683-75d78fa4cc0b/app.py
17/10/19 21:56:15 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://cluster-00686c:7077...
17/10/19 21:56:15 INFO TransportClientFactory: Successfully created connection to cluster-00686c/172.30.122.206:7077 after 30 ms (0 ms spent in bootstraps)
17/10/19 21:56:16 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20171019215615-0000
17/10/19 21:56:16 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40941.
17/10/19 21:56:16 INFO NettyBlockTransferService: Server created on 172.17.0.5:40941
17/10/19 21:56:16 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20171019215615-0000/0 on worker-20171019215548-172.17.0.13-46665 (172.17.0.13:46665) with 4 cores
17/10/19 21:56:16 INFO StandaloneSchedulerBackend: Granted executor ID app-20171019215615-0000/0 on hostPort 172.17.0.13:46665 with 4 cores, 1024.0 MB RAM
17/10/19 21:56:16 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
17/10/19 21:56:16 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 172.17.0.5, 40941, None)
17/10/19 21:56:16 INFO BlockManagerMasterEndpoint: Registering block manager 172.17.0.5:40941 with 366.3 MB RAM, BlockManagerId(driver, 172.17.0.5, 40941, None)
17/10/19 21:56:16 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 172.17.0.5, 40941, None)
17/10/19 21:56:16 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 172.17.0.5, 40941, None)
17/10/19 21:56:16 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20171019215615-0000/0 is now RUNNING
17/10/19 21:56:16 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
17/10/19 21:56:16 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/opt/app-root/src/spark-warehouse').
17/10/19 21:56:16 INFO SharedState: Warehouse path is 'file:/opt/app-root/src/spark-warehouse'.
17/10/19 21:56:17 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
17/10/19 21:56:17 INFO SparkContext: Starting job: reduce at /opt/app-root/src/app.py:31
17/10/19 21:56:17 INFO DAGScheduler: Got job 0 (reduce at /opt/app-root/src/app.py:31) with 2 output partitions
17/10/19 21:56:17 INFO DAGScheduler: Final stage: ResultStage 0 (reduce at /opt/app-root/src/app.py:31)
17/10/19 21:56:17 INFO DAGScheduler: Parents of final stage: List()
17/10/19 21:56:17 INFO DAGScheduler: Missing parents: List()
17/10/19 21:56:17 INFO DAGScheduler: Submitting ResultStage 0 (PythonRDD[1] at reduce at /opt/app-root/src/app.py:31), which has no missing parents
17/10/19 21:56:17 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 4.8 KB, free 366.3 MB)
17/10/19 21:56:18 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 3.2 KB, free 366.3 MB)
17/10/19 21:56:18 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 172.17.0.5:40941 (size: 3.2 KB, free: 366.3 MB)
17/10/19 21:56:18 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1006
17/10/19 21:56:18 INFO DAGScheduler: Submitting 2 missing tasks from ResultStage 0 (PythonRDD[1] at reduce at /opt/app-root/src/app.py:31) (first 15 tasks are for partitions Vector(0, 1))
17/10/19 21:56:18 INFO TaskSchedulerImpl: Adding task set 0.0 with 2 tasks
17/10/19 21:56:18 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.17.0.13:39988) with ID 0
17/10/19 21:56:18 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, 172.17.0.13, executor 0, partition 0, PROCESS_LOCAL, 4815 bytes)
17/10/19 21:56:18 INFO TaskSetManager: Starting task 1.0 in stage 0.0 (TID 1, 172.17.0.13, executor 0, partition 1, PROCESS_LOCAL, 4815 bytes)
17/10/19 21:56:18 INFO BlockManagerMasterEndpoint: Registering block manager 172.17.0.13:38923 with 366.3 MB RAM, BlockManagerId(0, 172.17.0.13, 38923, None)
17/10/19 21:56:19 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 172.17.0.13:38923 (size: 3.2 KB, free: 366.3 MB)
17/10/19 21:56:19 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, 172.17.0.13, executor 0): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/opt/spark/python/lib/pyspark.zip/pyspark/worker.py", line 166, in main
    func, profiler, deserializer, serializer = read_command(pickleSer, infile)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/worker.py", line 55, in read_command
    command = serializer._read_with_length(file)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 169, in _read_with_length
    return self.loads(obj)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 454, in loads
    return pickle.loads(obj)
ImportError: No module named werkzeug.test
```

I am wondering if there is something strange about the way the route handler gets serialized to the workers.

**Comment by zak-hassan** [comment]
Could it be missing an requirement in the requirement.txt ??  imho it could be coming from the image.

**Comment by elmiko** [comment]
good question, i don't think so though as the app will run sometimes. also the `werkzeug.test` is not a requirement, it's part of the flask deployment.

**Comment by elmiko** [comment]
this error will reliably happen for me when i create a new project in openshift and then instantiate the app through the suggested commands in the readme.

if i then delete the openshift project, recreate the project, then run the app, all the errors go away. i'm really confused about this.

**Comment by elmiko** [comment]
attaching a more thorough error log

[sparkpi-error.log](https://github.com/radanalyticsio/tutorial-sparkpi-python-flask/files/1446716/sparkpi-error.log)

**Comment by elmiko** [comment]
i think the issue is with the way spark attempts to pickle the closure around the activity. in *some* cases it tries to pull in the flask related imports, the change proposed in #10 will separate those functions more thoroughly.

**Comment by elmiko** [comment]
i'm re-opening this as the previous fix has now proven not to work in some environments

**Comment by elmiko** [comment]
so, i think what is happening is that when spark attempts to pickle the functions for the `parallelize` operation it scans the namespaces associated with the functions. since the `add` function must be pulled from an import at the top level, it appears that occasionally the pickler will run across the flask based import first and thus run into an error with werkzeug.test.

the change in #11 removes the `add` function and uses a lambda instead, which i postulate will force the pickler not to look at the file level.
